### ISSUE TITLE
skipping this file because the filename structure is not unknown...

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/encryption-recovery-tools#32]
Hi!

I am trying to use your recovery tool to decrypt the e2e encrypted files. Getting the error `skipping this file because the filename structure is not unknown...`

What can be wrong?

**Comment by ostasevych** [comment]
> @ostasevych I've seen that you have some debug entries like `DEBUG: metadata file has wrong structure`. Would be great to learn how these look like. They're either broken or have a structure that I haven't seen before.

I have checked them: they contained only checksum, metadataKey without the reference to a file... So, probably, orphans.

**Comment by yahesh** [comment]
@ostasevych 

> Well, according to you that is not so clear. I may not know the exact location of the file:

That's why I improved the documentation in https://github.com/nextcloud/encryption-recovery-tools/pull/34. Normally you don't have to provide the name of the `sourcedir` / `sourcefile` and instead just decrypt all of the files by omitting the parameter entirely.

> I managed to get the result by dirty patching

I really don't know what this is supposed to tell me.

**Comment by yahesh** [comment]
> Ah, it is just to say, that it is possible to decrypt data saved locally. I mean, in particular cases it may be good to have option to recover data from locally provided inputs, eg data and metadata. So, a user may copy from the server in his own folder both metadata and data and restore them by providing the mnemonics.

Yeah, sure. Just copy those in the same directory and set that directory as the `DATADIRECTORY`.

I guess this is fixed then.
