### ISSUE TITLE
decrypt all files script fails without error

### ISSUE THREAD

**Issue by Merlinux-source** [nextcloud/encryption-recovery-tools#39]
![Screenshot from 2024-03-08 13-56-02](https://github.com/nextcloud/encryption-recovery-tools/assets/67962212/05576789-991a-49a5-bef7-d15f16762611)
when decrypting files using the decrypt all files script, some files fail without any explanation to why.
how do I get more verbose information on what to do, so I can get my files back. I have backups of all keys and file versions, but the files are all encrypted using serverside encryption

**Comment by yahesh** [comment]
To get more verbose output you can enable the DEBUG_MODE. If that is insufficient you can additionally enable the DEBUG_MODE_VERBOSE.

**Comment by yahesh** [comment]
@Merlinux-source Has the issue been resolved for you?

**Comment by yahesh** [comment]
@Merlinux-source If there's no further support needed, I'd close this ticket at the end of this week.

**Comment by brandonb1987** [comment]
I too am having this issue. How do I enable verbose? I'm a noob.

**Comment by yahesh** [comment]
@brandonb1987 @Merlinux-source I now added `DEBUG_MODE` and `DEBUG_MODE_VERBOSE` to the documentation.

@brandonb1987 You can either provide the values als environment variables during execution `DEBUG_MODE=true DEBUG_MODE_VERBOSE=true ./recover.php [...]` or you can scroll down, uncomment the corresponding `config()` calls and set the value to `true` there:

* https://github.com/nextcloud/encryption-recovery-tools/blob/9badf234dfeda484eac25f6470f2e31954a3b3a6/end-to-end-encryption/recover.php#L183-L184
* https://github.com/nextcloud/encryption-recovery-tools/blob/9badf234dfeda484eac25f6470f2e31954a3b3a6/server-side-encryption/recover.php#L236-L237
